package com.univer.dbproject;

public enum Command {
    ADD_AUTHOR,
    ADD_DISHES_FAMILY,
    ADD_INGREDIENT,
    ADD_RECIPE,
    ADD_INGREDIENT_IN_RECIPE,

    DELETE_AUTHOR,
    DELETE_DISHES_FAMILY,
    DELETE_INGREDIENT,
    DELETE_RECIPE,
    DELETE_INGREDIENT_FROM_RECIPE,

    UPDATE_AUTHOR,
    UPDATE_DISHES_FAMILY,
    UPDATE_INGREDIENT,
    UPDATE_RECIPE,
    UPDATE_INGREDIENT_IN_RECIPE,

    TAKE_AUTHOR_BY_KEY,
    TAKE_DISHES_FAMILY_BY_KEY,
    TAKE_INGREDIENT_BY_KEY,
    TAKE_RECIPE_BY_KEY,
    TAKE_INGREDIENT_FROM_RECIPE_BY_KEY,

    TAKE_ALL_AUTHOR,
    TAKE_ALL_DISHES_FAMILY,
    TAKE_ALL_INGREDIENT,
    TAKE_ALL_RECIPE,
    TAKE_ALL_INGREDIENT_FROM_RECIPE,
}
